# Generated by Django 3.0.2 on 2020-06-07 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Education', '0002_auto_20200607_1654'),
    ]

    operations = [
        migrations.CreateModel(
            name='contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phno', models.CharField(max_length=11)),
                ('msg', models.TextField()),
            ],
        ),
    ]
