# Generated by Django 3.0.2 on 2020-06-09 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Education', '0005_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='duration',
            field=models.CharField(default=2, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='startdate',
            field=models.CharField(default=3, max_length=100),
            preserve_default=False,
        ),
    ]
