# Generated by Django 3.0.2 on 2020-06-09 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Education', '0007_course_trainer'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='link',
            field=models.CharField(default=2, max_length=100),
            preserve_default=False,
        ),
    ]
